services:
  - type: web
    name: sismatias
    env: node
    buildCommand: npm install && npm run build
    startCommand: node .next/standalone/server.js
    routes:
      - type: rewrite
        source: /*
        destination: /
